## Numpy Usage

In [9]:
import numpy as np # importing the Numpy package
a = np.array([1, 4, 5, 8], float) # Creating Numpy array with Float variables
print(type(a))

<class 'numpy.ndarray'>


### Operations on the array

In [11]:
a[0] = 5 # Replacing the first element of the array
print(a)

[5. 4. 5. 8.]


In [12]:
b = np.array([[1, 2, 3], [4, 5, 6]], float) # Creating a 2-D numpy array
b[0, 1] # Fetching second element of 1st array

2.0

In [13]:
print(b.shape) # Returns tuple with the shape of array

(2, 3)


In [14]:
b.dtype # Returns the type of the value stored

dtype('float64')

In [15]:
print(len(b)) # Returns length of the first axis

2


In [16]:
2 in b # 'in' searches for the element in the array

True

In [17]:
0 in b

False

### Use of 'reshape' : transforms elements from 1-D to 2-D here

In [18]:
c = np.array(range(12), float)
print(c)
print(c.shape)
print('---')
c = c.reshape((2, 6)) # reshape the array in the new form
print(c)
print(c.shape)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
(12,)
---
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
(2, 6)


In [19]:
c.fill(0) # Fills whole array with single value, done inplace
print(c)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [20]:
c.transpose() # creates transpose of the array, not done inplace

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.array([[0., 0.], [0., 0.], [0., 0.], [0., 0.], [0., 0.], [0., 0.]])
c.flatten() # flattens the whole array, not done inplace

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Concatenation of 2 or more arrays

In [24]:
m = np.array([1, 2], float)
n = np.array([3, 4, 5, 6], float)
p = np.concatenate((m, n))
print(p)
print(p.shape)

[1. 2. 3. 4. 5. 6.]
(6,)


### 'newaxis' : to increase the dimensonality of the array

In [35]:
q = np.array([1, 2, 3], float)
print(q)
print(q.shape)


[1. 2. 3.]
(3,)


In [36]:
q = q[:, np.newaxis]
print(q)
print(q.shape)

[[1.]
 [2.]
 [3.]]
(3, 1)


### zeros()

In [41]:
zeros_array = np.zeros([4, 2])
print(zeros_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [44]:
ones_array = np.ones([4, 2])
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [48]:
zeros_like_array = np.zeros_like([[5, 6, 7], [1, 2, 3]])
print(zeros_like_array)

[[0 0 0]
 [0 0 0]]


In [49]:
ones_like_array = np.ones_like([[5, 6, 7], [1, 2, 3]])
print(ones_like_array)

[[1 1 1]
 [1 1 1]]


In [58]:
identity_array = np.identity(4) # identity(4, 3) is error
print(identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [57]:
eye_array = np.eye(4, 3)
print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


### times

In [60]:
a1 = np.array([[1, 2], [3, 4], [5, 6]], float)
a2 = np.array([-1, 3], float)
print(a1+a2) 

[[0. 5.]
 [2. 7.]
 [4. 9.]]


In [63]:
print(np.pi) # pi saved as constant in Numpy
print(np.e)  # e saved as constant in Numpy

3.141592653589793
2.718281828459045


### sum(和) prod(积) mean var(方差) std(标准差) argmin(最小元素索引) 
### argmax(最大元素索引) sort(排序) unique(唯一元素)

In [65]:
a3 = np.array([[0, 2], [3, -1], [3, 5]], float)
# 都需要axis属性
print(a3.mean(axis=0)) # Mean of elements column-wise
print(a3.mean(axis=1)) # Mean of elements row-wise 

[2. 2.]
[1. 1. 4.]


### nonzero(检查非零元素) isnan(检查“非数字”元素) isfinite(检查有限元素)

In [104]:
a = np.array([1, 4, 5, 8], float)
a4 = np.array([1, 3, 0], float)
print(np.where(a!=0, 1/a, a))
print(np.where(a4!=0, 2*a4, -a4)) # np.where(condition, x, y), 如果条件满足x, 否则y

[1.    0.25  0.2   0.125]
[ 2.  6. -0.]


### random(随机数)

In [106]:
np.random.seed(1234) 
np.random.rand(2, 3) # 通过马特赛特旋转算法生成伪随机数

array([[0.19151945, 0.62210877, 0.43772774],
       [0.78535858, 0.77997581, 0.27259261]])