## Scipy Usage
### Scipy 提供了负责的算法及其在Numpy中作为函数的用法。
### 这将分配高级命令和多种多样的类来操作和可视化数据。
### Scipy 将多个小型包整合在一起，每个包都针对单独的科学计算领域。
### 其中的集合子包是 linalg(线性代数)、constants(物理和数学常数)、sparse(稀疏矩阵和相关例程)
### Numpy包中大多数针对数组的函数也包含在Scipy包中。
### Scipy提供预先测试好的例程，因此可以在科学计算应用中节省大量处理时间。

In [1]:
import scipy
import numpy as np 
from scipy import linalg # 线性代数子包
mat_ = np.array([[2, 3, 1], [4, 9, 10], [10, 5, 6]]) 
print(mat_)

[[ 2  3  1]
 [ 4  9 10]
 [10  5  6]]


In [3]:
print(linalg.det(mat_)) # Determinant of the matrix 矩阵行列式
inv_mat = linalg.inv(mat_) # Inverse of the matrix 矩阵的逆
print(inv_mat)

166.0
[[ 0.02409639 -0.07831325  0.12650602]
 [ 0.45783133  0.01204819 -0.09638554]
 [-0.42168675  0.12048193  0.03614458]]


### Singular Value Decomposition 奇异值分解

In [4]:
comp_1, comp_2, comp_3 = linalg.svd(mat_)
print(comp_1)
print(comp_2)
print(comp_3)

[[-0.1854159   0.0294175  -0.98221971]
 [-0.73602677 -0.66641413  0.11898237]
 [-0.65106493  0.74500122  0.14521585]]
[18.34661713  5.73710697  1.57709968]
[[-0.53555313 -0.56881403 -0.62420625]
 [ 0.84418693 -0.38076134 -0.37731848]
 [-0.02304957 -0.72902085  0.6841033 ]]


### Scipy.stats是一个大型子包，包含各种各样的统计分布处理函数，可用于操作不同类型的数据集

### Scipy stats module

In [5]:
from scipy import stats

### Generating a random sample of size 20 from normal distribution with mean 3 and standard deviation 5
### 从正态分布生成大小为20的随机样本，平均值为3，标准差为5

In [7]:
rvs_20 = stats.norm.rvs(3, 5, size=20)
print(rvs_20, '\n ---')

[ 5.0561557   5.14251437  0.37742247 -2.61685362  0.06781688  4.06539541
 -1.07715695 -2.68282799  5.19230001  1.88853363 -2.04002443  5.72558164
 -3.32820989 -5.54297017  8.51599397  4.24338853 -1.62284822  5.22029639
 -3.19899615  7.9937774 ] 
 ---


### Computing the CDF of Beta distribution with a=100 and b=130 as shape parameters at random variable 0.41
### CDF(Cumulative Distribution Function)累積分布函數，又叫分布函數，是概率密度函數的積分

In [11]:
cdf_ = stats.beta.cdf(0.41, a=100, b=130)
print(cdf_)

0.22500957436155394


### 有关使用Scipy子包的用法，参考http://docs.scipy.org/doc/